name: Release Automatic

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, next ]


jobs:
  wait-for-workflows:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: int128/wait-for-workflows-action@v1.17.0
        with:
          token: ${{ secrets.PAT_GLOBAL }}
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: wait-for-workflows
    steps:
      - name: Fake step
        run: |
          echo "Run the release job"

